Add files via upload
HL7Norway/basisprofiler-r4 pull request #95
Opened 2021-11-17 13:47 UTC by oaassv

2021-11-17 14:12 UTC, thomiz commented
Har ikke sett igjennom i detalj, to spørsmål @oaassv :
* Hva betyr det at flere profiler ikke heter no-basis?
* Navngivningen er ikke i tråd med prinsipper no-basis.

2021-11-18 09:53 UTC, thomiz commented
Dette går ikke gjennom build prosessen:
https://github.com/thomiz/fsh-no-basis/runs/4249565347?check_suite_focus=true

Dere må holde extensions id'er til lowercase, uten camelcase. både i extension.id og filnavn. Da er det kanskje også like greit å holde det lowercase også i profilene som henviser til disse extensions.

2021-11-19 07:06 UTC, rockphotog reviewed
Er dette et utkast på noe som ikke bør legges til master?

2021-11-19 07:13 UTC, oaassv commented
Ligger på egen Appointment branch
    På fredag 19. november 2021, 08:06:35 CET skrev Espen Stranger Seland ***@***.***> følgende:  
 
 


@rockphotog commented on this pull request.

Er dette et utkast på noe som ikke bør legges til master?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-19 12:52 UTC, thomiz requested changes
Det mangler fremdeles description i definisjonene (StructureDefinition)
Alle filene med dokumentasjon må ha endelse ".md"

2021-11-20 15:48 UTC, thomiz commented
> Er dette et utkast på noe som ikke bør legges til master?
> 
> Extensions må gjennomgås om de er aktuelle for basisprofiler vs områdeprofil.

@rockphotog Er det andre ting i branchen du tenker vi må gjøre før vi eventuelt pusher innholdet til master?

Når endringene har vært på høring og er godkjent kan vi lage en ny release som erstatter v2.1.1 av no-basis. Det vil da bli versjon 2.2.0.

2021-11-23 08:28 UTC, thomiz submitted a review, later dismissed

2021-11-23 12:51 UTC, thomiz commented
Denne pull'en er nå bare rot, med doble filer blant annet. 

Kan dere rydde opp og lage en ny pull request, eventuelt basert på en ny branch. @oaassv @lfreddy

2021-11-23 12:51 UTC, closed without merging